### ISSUE TITLE
Error Setting Up Client

### ISSUE THREAD

**Issue by Coolie1101** [armills/aioautomatic#2]
* aioautomatic version: 0.4.0
* Python version: 3.4
* Operating System: HASSBIAN

### Description

After upgrading HASS to 0.50.2, I started getting the following errors.

```

ERROR (MainThread) [homeassistant.components.device_tracker.automatic] err_invalid_client
ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform automatic
```

The issue is being discussed in the community @ https://community.home-assistant.io/t/automatic-odb-ii-issue/3813/57?u=coolie1101

**Comment by tchellomello** [comment]
+1 here. Hitting the same problem

**Comment by jamieshaw** [comment]
Experienced this issue too. Have already opened on against [Home Assistant](https://github.com/home-assistant/home-assistant/issues/8803) itself.

I'm suspecting that the password authorisation is no longer supported, and they're going whole hog with token OAuth.

**Comment by rpitera** [comment]
I added to Jamie's issue here:
https://github.com/home-assistant/home-assistant/issues/8803

**Comment by rpitera** [comment]
Confirm that OAuth2 is now **required**.   Just looked at this page:
https://developer.automatic.com/api-reference/#support

**Comment by armills** [comment]
Good to know. `aioautomatic` should already support OAuth2 login mode, and I'll just remove the password authentication if it's no longer accepted. We can discuss hass issues in home-assistant/home-assistant#8803 .

**Comment by rpitera** [comment]
Thanks for looking into this Adam!

**Comment by armills** [comment]
Dropped `Client.create_session_from_password` and polished up OAuth2 workflow as of 0.6.0.
